version: '3.8'

services:
  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .envrc
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: testpostgres
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
